name: Reassure Performance Tests
'on':
  pull_request:
    types:
    - opened
    - synchronize
    branches-ignore:
    - staging
    - production
    paths-ignore:
    - docs/**
    - help/**
    - .github/**
    - contributingGuides/**
    - tests/**
    - '**.md'
    - '**.sh'
jobs:
  perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        fetch-depth: 0
    - name: Setup NodeJS
      uses: ./.github/actions/composite/setupNode
    - name: Set dummy git credentials
      run: 'git config --global user.email "test@test.com"

        git config --global user.name "Test"

        '
    - name: Get common ancestor commit
      run: 'git fetch origin main

        common_ancestor=$(git merge-base "${{ github.sha }}" origin/main)

        echo "COMMIT_HASH=$common_ancestor" >> "$GITHUB_ENV"

        '
    - name: Clean up deleted files
      run: "DELETED_FILES=$(git diff --name-only --diff-filter=D \"$COMMIT_HASH\"\
        \ \"${{ github.sha }}\")\nfor file in $DELETED_FILES; do\n  if [ -n \"$file\"\
        \ ]; then\n    rm -f \"$file\"\n    echo \"Deleted file: $file\"\n  fi\ndone\n"
    - name: Run performance testing script
      shell: bash
      run: "set -e\nBASELINE_BRANCH=${BASELINE_BRANCH:=\"main\"}\ngit fetch origin\
        \ \"$BASELINE_BRANCH\" --no-tags --depth=1\ngit switch \"$BASELINE_BRANCH\"\
        \ncd Mobile-Expensify\ngit checkout \"$(git rev-parse HEAD)\"\ncd ..\ngit\
        \ add Mobile-Expensify\nnpm install --force || (rm -rf node_modules && npm\
        \ install --force) \nNODE_OPTIONS=--experimental-vm-modules npx reassure --baseline\n\
        git switch --force --detach -\ncd Mobile-Expensify\ngit checkout \"$(git rev-parse\
        \ HEAD)\"\ncd ..\ngit add Mobile-Expensify\ngit merge --no-commit --allow-unrelated-histories\
        \ \"$BASELINE_BRANCH\" -X ours\ngit checkout --ours .\nnpm install --force\
        \ || (rm -rf node_modules && npm install --force)\nNODE_OPTIONS=--experimental-vm-modules\
        \ npx reassure --branch\n"
    - name: Validate output.json
      id: validateReassureOutput
      uses: ./.github/actions/javascript/validateReassureOutput
      with:
        DURATION_DEVIATION_PERCENTAGE: 20
        COUNT_DEVIATION: 0
